enabled: true

# Should the plugin ignore things such as chests that have naturally generated
# (Subinterfaces of https://jd.papermc.io/paper/1.21.11/com/destroystokyo/paper/loottable/LootableBlockInventory.html)
ignore-natural-lootables: true

friends:
  command-aliases:
    - friend

villagers:
  enabled: true # Will the plugin function for villagers?
  command-aliases:
    - pv
  timeout: 10 # Timeout duration for after player runs the protect villager command.
  apply-glow-on-register: true # Will villagers be given the glow effect for 1 second when their owner is registered

ignored-materials:
  - ACACIA_SHELF
  - ACACIA_SIGN
  - ACACIA_WALL_SIGN
  - BAMBOO_SHELF
  - BAMBOO_SIGN
  - BAMBOO_WALL_SIGN
  - BEEHIVE
  - BELL
  - BIRCH_SHELF
  - BIRCH_SIGN
  - BIRCH_WALL_SIGN
  - BLACK_BANNER
  - BLACK_BED
  - BLACK_WALL_BANNER
  - BLUE_BANNER
  - BLUE_BED
  - BLUE_WALL_BANNER
  - BROWN_BANNER
  - BROWN_BED
  - BROWN_WALL_BANNER
  - CALIBRATED_SCULK_SENSOR
  - CHAIN_COMMAND_BLOCK
  - CHERRY_SHELF
  - CHERRY_SIGN
  - CHERRY_WALL_SIGN
  - CHISELED_BOOKSHELF
  - COMMAND_BLOCK
  - COMPARATOR
  - COPPER_GOLEM_STATUE
  - CREAKING_HEART
  - CREEPER_HEAD
  - CRIMSON_SHELF
  - CRIMSON_SIGN
  - CRIMSON_WALL_SIGN
  - CYAN_BANNER
  - CYAN_BED
  - CYAN_WALL_BANNER
  - DARK_OAK_SHELF
  - DARK_OAK_SIGN
  - DARK_OAK_WALL_SIGN
  - DAYLIGHT_DETECTOR
  - DECORATED_POT
  - DRAGON_HEAD
  - ENCHANTING_TABLE
  - END_GATEWAY
  - ENDER_CHEST
  - EXPOSED_COPPER_GOLEM_STATUE
  - GRAY_BANNER
  - GRAY_BED
  - GRAY_WALL_BANNER
  - GREEN_BANNER
  - GREEN_BED
  - GREEN_WALL_BANNER
  - JUNGLE_SHELF
  - JUNGLE_SIGN
  - JUNGLE_WALL_SIGN
  - LIGHT_BLUE_BANNER
  - LIGHT_BLUE_BED
  - LIGHT_BLUE_WALL_BANNER
  - LIGHT_GRAY_BANNER
  - LIGHT_GRAY_BED
  - LIGHT_GRAY_WALL_BANNER
  - LIME_BANNER
  - LIME_BED
  - LIME_WALL_BANNER
  - MAGENTA_BANNER
  - MAGENTA_BED
  - MAGENTA_WALL_BANNER
  - MANGROVE_SHELF
  - MANGROVE_SIGN
  - MANGROVE_WALL_SIGN
  - OAK_SHELF
  - OAK_SIGN
  - OAK_WALL_SIGN
  - ORANGE_BANNER
  - ORANGE_BED
  - ORANGE_WALL_BANNER
  - OXIDIZED_COPPER_GOLEM_STATUE
  - PALE_OAK_SHELF
  - PALE_OAK_SIGN
  - PALE_OAK_WALL_SIGN
  - PIGLIN_HEAD
  - PINK_BANNER
  - PINK_BED
  - PINK_WALL_BANNER
  - PLAYER_HEAD
  - PURPLE_BANNER
  - PURPLE_BED
  - PURPLE_WALL_BANNER
  - RED_BANNER
  - RED_BED
  - RED_WALL_BANNER
  - REPEATING_COMMAND_BLOCK
  - SCULK_CATALYST
  - SCULK_SENSOR
  - SCULK_SHRIEKER
  - SKELETON_SKULL
  - SPAWNER
  - SPRUCE_SHELF
  - SPRUCE_SIGN
  - SPRUCE_WALL_SIGN
  - SUSPICIOUS_GRAVEL
  - SUSPICIOUS_SAND
  - TRIAL_SPAWNER
  - VAULT
  - WARPED_SHELF
  - WARPED_SIGN
  - WARPED_WALL_SIGN
  - WAXED_COPPER_GOLEM_STATUE
  - WAXED_EXPOSED_COPPER_GOLEM_STATUE
  - WAXED_OXIDIZED_COPPER_GOLEM_STATUE
  - WAXED_WEATHERED_COPPER_GOLEM_STATUE
  - WEATHERED_COPPER_GOLEM_STATUE
  - WHITE_BANNER
  - WHITE_BED
  - WHITE_WALL_BANNER
  - WITHER_SKELETON_SKULL
  - YELLOW_BANNER
  - YELLOW_BED
  - YELLOW_WALL_BANNER
  - ZOMBIE_HEAD
